version: 2.1


commands:
    setup_node_modules:
        steps:
            - run: sudo apt update
            - run: sudo apt install -y npm
            - run: sudo npm cache clean -f
            - run: sudo npm install -g n
            - run: sudo n stable
            - run:
                name: Install static type checker
                command: npm ci


jobs:
    run_check:
        docker:
            - image: circleci/python:3.8.3-buster
        steps:
            - checkout
            - setup_node_modules
            - run:
                name: Run check
                command: make check


workflows:
    test:
        jobs:
            - run_check
